name: main

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Publish test coverage report
        uses: benc-uk/workflow-dispatch@v1.1.0
        with:
          repo: BillKalaitzis/repo2
          ref: refs/heads/main
          workflow: main.yml
          token: ${{ secrets.TOKEN }}
          inputs: '{}'
